kind: Deployment
apiVersion: apps/v1
metadata:
  name: ovnkube-master
  namespace: openshift-ovn-kubernetes
  annotations:
    kubernetes.io/description: |
      This daemonset launches the ovn-kubernetes controller (master) networking components.
    release.openshift.io/version: "{{.ReleaseVersion}}"
spec:
  replicas: 3
  selector:
    matchLabels:
      name: ovnkube-master
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # by default, Deployments spin up the new pod before terminating the old one
      # but we don't want that - because ovsdb holds the lock.
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: ovnkube-master
        component: network
        type: infra
        openshift.io/component: network
        kubernetes.io/os: "linux"
    spec:
      serviceAccountName: ovn-kubernetes-controller
      hostNetwork: true
      priorityClassName: "system-cluster-critical"
      # volumes in all containers:
      # (container) -> (host)
      # /etc/openvswitch -> /var/lib/ovn/etc - ovsdb data
      # /var/lib/openvswitch -> /var/lib/ovn/data - ovsdb pki state
      # /run/openvswitch -> tmpfs - sockets & pids
      # /env -> configmap env-overrides - debug overrides
      containers:
      # ovn-northd: convert network objects in nbdb to flows in sbdb
      - name: northd
        image: {{.OvnImage}}
        command:
        - /bin/bash
        - -c
        - |
          set -e
          if [[ -f /env/_master ]]; then
            set -o allexport
            source /env/_master
            set +o allexport
          fi
          exec ovn-northd --no-chdir "-vconsole:${OVN_LOG_LEVEL}" -vfile:off --pidfile=/var/run/openvswitch/ovn-northd.pid --unixctl=ovn-northd.ctl
        env:
        - name: OVN_LOG_LEVEL
          value: info
        volumeMounts:
        - mountPath: /etc/openvswitch/
          name: etc-openvswitch
        - mountPath: /var/lib/openvswitch/
          name: var-lib-openvswitch
        - mountPath: /run/openvswitch/
          name: run-openvswitch
        - mountPath: /env
          name: env-overrides
        resources:
          requests:
            cpu: 100m
            memory: 300Mi

      # nbdb: the northbound, or logical network object DB
      - name: nbdb
        image: {{.OvnImage}}
        command:
        - /bin/bash
        - -c
        - |
          set -e
          if [[ -f /env/_master ]]; then
            set -o allexport
            source /env/_master
            set +o allexport
          fi
          exec /usr/share/openvswitch/scripts/ovn-ctl run_nb_ovsdb \
            --no-monitor \
            --ovn-nb-log="-vconsole:${OVN_LOG_LEVEL} -vfile:off"
        env:
        - name: OVN_LOG_LEVEL
          value: info
        volumeMounts:
        - mountPath: /etc/openvswitch/
          name: etc-openvswitch
        - mountPath: /var/lib/openvswitch/
          name: var-lib-openvswitch
        - mountPath: /run/openvswitch/
          name: run-openvswitch
        - mountPath: /env
          name: env-overrides
        resources:
          requests:
            cpu: 100m
            memory: 300Mi

      # sbdb: the southbound, or flow DB
      - name: sbdb
        image: {{.OvnImage}}
        command:
        - /bin/bash
        - -c
        - |
          set -e
          if [[ -f "/env/_master" ]]; then
            set -o allexport
            source "/env/_master"
            set +o allexport
          fi
          exec /usr/share/openvswitch/scripts/ovn-ctl run_sb_ovsdb \
            --no-monitor \
            --ovn-nb-log="-vconsole:${OVN_LOG_LEVEL} -vfile:off"
        env:
        - name: OVN_LOG_LEVEL
          value: info
        volumeMounts:
        - mountPath: /etc/openvswitch/
          name: etc-openvswitch
        - mountPath: /var/lib/openvswitch/
          name: var-lib-openvswitch
        - mountPath: /run/openvswitch/
          name: run-openvswitch
        - mountPath: /env
          name: env-overrides

      # ovnkube master: convert kubernetes objects in to nbdb logical network components
      - name: ovnkube-master
        image: {{.OvnImage}}
        command:
        - /bin/bash
        - -c
        - |
          set -e
          if [[ -f "/env/_master" ]]; then
            set -o allexport
            source "/env/_master"
            set +o allexport
          fi
          exec /usr/bin/ovnkube \
            --init-master "${K8S_NODE}" \
            --cluster-subnets "${OVN_NET_CIDR}" \
            --k8s-service-cidr "${OVN_SVC_CIDR}" \
            --k8s-apiserver "{{.K8S_APISERVER}}" \
            --ovn-config-namespace openshift-ovn-kubernetes \
            --nodeport \
            --loglevel "${OVN_KUBE_LOG_LEVEL}" \
            --logfile /dev/stdout \
            --manage-db-servers \
            --pod-ip "${POD_IP}" \
            --nb-port "{{.OVN_NB_PORT}}" \
            --sb-port "{{.OVN_SB_PORT}}"
        volumeMounts:
        - mountPath: /etc/openvswitch/
          name: etc-openvswitch
        - mountPath: /var/lib/openvswitch/
          name: var-lib-openvswitch
        - mountPath: /run/openvswitch/
          name: run-openvswitch
        - mountPath: /env
          name: env-overrides
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: OVN_KUBE_LOG_LEVEL
          value: "4"
        - name: OVN_NET_CIDR
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: net_cidr
        - name: OVN_SVC_CIDR
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: svc_cidr
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      nodeSelector:
        node-role.kubernetes.io/master: ""
        beta.kubernetes.io/os: "linux"
      volumes:
      - name: etc-openvswitch
        hostPath:
          path: /var/lib/ovn/etc
      - name: var-lib-openvswitch
        hostPath:
          path: /var/lib/ovn/data
      - name: run-openvswitch
        emptyDir: {}
      - name: env-overrides
        configMap:
          name: env-overrides
          optional: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
